stages:
  - prepare
  - build
  - test
  - release
  - deploy

variables:
  DOCKER_REGISTRY: "registry.gitlab.com"
  TEST_IMAGE: "$DOCKER_REGISTRY/$DOCKER_USERNAME/sahabee/test:0.1.0"


build-test-image:
  stage: prepare
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  script:
    - cd test/
    - docker build -t $TEST_IMAGE .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker push $TEST_IMAGE
  when: manual

build:
  stage: build
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION="snapshot-${CI_COMMIT_SHA}"
  script:
    - docker-compose build
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker-compose push

test:
  stage: test
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION="snapshot-${CI_COMMIT_SHA}"
  script:
    - docker-compose pull
    - docker-compose up -d --no-build
    - cd test/
    - docker run --net host -v `pwd`/test.py:/tmp/test.py $TEST_IMAGE /tmp/test.py
