stages:
  - prepare
  - build
  - test
  - release
  - deploy

variables:
  IMAGE_PREFIX: "registry.gitlab.com/emran.bm/sahabee"
  API_IMAGE_NAME: "${IMAGE_PREFIX}/api"
  FRONTEND_IMAGE_NAME: "${IMAGE_PREFIX}/frontend"
  API_IMAGE_RELEASE_VERSION: "0.3.1"
  FRONTEND_IMAGE_RELEASE_VERSION: "${CI_COMMIT_SHA}"
  SNAPSHOT_VERSION: "snapshot-${CI_COMMIT_SHA}"

build:
  stage: build
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION=$SNAPSHOT_VERSION
    - export FRONTEND_VERSION=$SNAPSHOT_VERSION
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin registry.gitlab.com
    - docker-compose build
    - docker-compose push
  except:
    - schedules

test-api:
  stage: test
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION=$SNAPSHOT_VERSION
    - export FRONTEND_VERSION=$SNAPSHOT_VERSION
  variables:
    COMPOSE_INTERACTIVE_NO_CLI: 'true'
  script:
    - docker-compose pull api
    - docker-compose run --name test_container api ./manage.py test
    - docker cp test_container:/sahabee/.coverage .
  artifacts:
    reports:
      cobertura: .coverage
  needs:
    - build
  except:
    - schedules

test-ansible:
  stage: test
  tags:
    - docker
  image: spy86/ansible:latest
  services:
    - name: rastasheep/ubuntu-sshd:18.04
      alias: sahabee.ir
  script:
    - DNS_SERVER=`cat /etc/resolv.conf | grep -m 1 nameserver | cut -d' ' -f2`
    - cd deployment/ansible/
    - ansible-playbook infra.yml -i inventory.yml -vvv
      --limit test
      --extra-vars "shecan_dns_1=$DNS_SERVER shecan_dns_2=$DNS_SERVER"
    - ansible-playbook deploy.yml -i inventory.yml -vvv --limit test
    - curl -i --fail https://sahabee.ir
  only:
    changes:
      - deployment/ansible/*
      - .gitlab-ci.yml
  except:
    - schedules

release:
  stage: release
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION=$SNAPSHOT_VERSION
    - export FRONTEND_VERSION=$SNAPSHOT_VERSION
  script:
    - docker-compose pull api frontend
    - docker tag ${API_IMAGE_NAME}:${API_VERSION} ${API_IMAGE_NAME}:${API_IMAGE_RELEASE_VERSION}
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin registry.gitlab.com
    - docker push ${API_IMAGE_NAME}:${API_IMAGE_RELEASE_VERSION}
  only:
    refs:
      - master
  except:
    - schedules

setup-infra:
  stage: deploy
  tags:
    - docker
  image: spy86/ansible:latest
  script:
    - cd deployment/ansible/
    - ansible-playbook infra.yml -i inventory.yml --limit production
  when: manual
  only:
    refs:
      - master
  except:
    - schedules

deploy:
  stage: deploy
  tags:
    - docker
  image: spy86/ansible:latest
  script:
    - cd deployment/ansible/
    - ansible-playbook deploy.yml -i inventory.yml --limit production
  artifacts:
    paths:
      - deployment/ansible/smoke-test-result.txt
    when: on_failure
    expire_in: 1 week
  only:
    refs:
      - master
  environment:
    name: production
    url: https://sahabee.ir
  except:
    - schedules

clean-gitlab-registry:
  tags:
    - docker
  image: nyurik/alpine-python3-requests
  script:
    - ./ci-utils/clean-docker-registry.py
      --project-id ${CI_PROJECT_ID}
      --access-token ${DOCKER_REGISTRY_CLEAN_JOB_API_TOKEN}
      --repo ${API_IMAGE_NAME}
      --prefix "snapshot-"
    - ./ci-utils/clean-docker-registry.py
      --project-id ${CI_PROJECT_ID}
      --access-token ${DOCKER_REGISTRY_CLEAN_JOB_API_TOKEN}
      --repo ${FRONTEND_IMAGE_NAME}
      --prefix "snapshot-"
  only:
    - schedules

