stages:
  - prepare
  - build
  - test
  - release
  - deploy

variables:
  DOCKER_REGISTRY: "registry.gitlab.com"
  TEST_IMAGE: "$DOCKER_REGISTRY/$DOCKER_USERNAME/sahabee/test:0.2.0"
  API_IMAGE_NAME: "registry.gitlab.com/emran.bm/sahabee/api"
  API_IMAGE_RELEASE_VERSION: "0.3.0"
  DEPLOYMENT_DOCKER: "${DOCKER_REGISTRY}/$DOCKER_USERNAME/sahabee/deployment-image:0.3.0"

create-deployment-image:
  stage: prepare
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - cd deployment/
    - docker build -t $DEPLOYMENT_DOCKER .
    - docker push $DEPLOYMENT_DOCKER
  when: manual
  only:
    refs:
      - master

add-public-key-to-machines:
  stage: deploy
  tags:
    - docker
  image: $DEPLOYMENT_DOCKER
  script:
    - cd deployment/
    - cp ~/.ssh/id_rsa.pub .
    - ./add-public-key.sh
      --server $SSH_PROXY_IP
      --user $SSH_PROXY_SERVER_USER
      --pass $SSH_PROXY_SERVER_PASS
      --no-check-fingerprint
    - scp ./add-public-key.sh ./id_rsa.pub ${SSH_PROXY_SERVER_USER}@${SSH_PROXY_IP}:/tmp/
    - ssh ${SSH_PROXY_SERVER_USER}@${SSH_PROXY_IP} "/tmp/add-public-key.sh --server $SERVER_PROD_IP --user $SERVER_PROD_USER --pass $SERVER_PROD_PASS --no-check-fingerprint"
  when: manual
  only:
    refs:
      - master

build-test-image:
  stage: prepare
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  script:
    - cd test/
    - docker build -t $TEST_IMAGE .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker push $TEST_IMAGE
  when: manual

build:
  stage: build
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION="snapshot-${CI_COMMIT_SHA}"
  script:
    - docker-compose build
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker-compose push

test:
  stage: test
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION="snapshot-${CI_COMMIT_SHA}"
  variables:
    TEST_USER: 'test'
    TEST_PASS: 'test'
    COMPOSE_INTERACTIVE_NO_CLI: 'true'
  script:
    - docker-compose pull
    - docker-compose up -d --no-build
    - sleep 15
    - docker exec sahabee_api_1 bash -c
      "echo \"from django.contrib.auth import get_user_model; User = get_user_model(); user = User.objects.create_superuser('$TEST_USER', 'a@b.com', '$TEST_PASS', first_name='سردار', last_name='آزمون'); from rollcall.models import UserDetail; UserDetail.objects.create(user=user,personnel_code='1234',manager_name='علی',unit='QD')\" | ./manage.py shell"
    - cd test/
    - docker run --env TEST_USER --env TEST_PASS --net host -v `pwd`/test.py:/tmp/test.py $TEST_IMAGE /tmp/test.py

release:
  stage: release
  image: docker/compose:1.25.4
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - export API_VERSION="snapshot-${CI_COMMIT_SHA}"
  script:
    - docker-compose pull api
    - docker tag ${API_IMAGE_NAME}:${API_VERSION} ${API_IMAGE_NAME}:${API_IMAGE_RELEASE_VERSION}
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker push ${API_IMAGE_NAME}:${API_IMAGE_RELEASE_VERSION}
  only:
    refs:
      - master

setup-infra:
  stage: deploy
  tags:
    - docker
  image: $DEPLOYMENT_DOCKER
  script:
    - cd deployment/ansible/
    - ansible-playbook infra.yml -i inventory.yml -vvv
  when: manual
  only:
    refs:
      - master

deploy:
  stage: deploy
  tags:
    - docker
  image: $DEPLOYMENT_DOCKER
  script:
    - cd deployment/ansible/
    - ansible-playbook deploy.yml -i inventory.yml -vvv
  artifacts:
    paths:
      - deployment/ansible/smoke-test-result.txt
    when: on_failure
    expire_in: 1 week
  only:
    refs:
      - master
  environment:
    name: production
    url: https://sahabee.ir/admin
