---
- hosts: all
  tasks:
    - name: 'Stop containers'
      docker_compose:
        project_src: '{{ dest_root_dir }}'
        build: no
        pull: no
        state: absent
      environment:
        API_VERSION: '{{ api_version }}'
        PRODUCTION_IP: '{{ ansible_host }}'
        SECRET_KEY: '{{ secret_key }}'
        FULLCHAIN_PATH: /etc/sahabee.ir/ssl-files/fullchain.pem
        PRIVKEY_PATH: /etc/sahabee.ir/ssl-files/privkey.pem