---
- hosts: all
  tasks:
    - name: 'Copy compose file'
      copy:
        src: '{{ src_root_dir }}/docker-compose.yml'
        dest: '/home/{{ ansible_user }}/sahabee/'
    - name: 'Create build directories as a hack to make docker-compose work!'
      file:
        path: /home/{{ ansible_user }}/sahabee/{{ item }}
        state: directory
      loop:
        - 'backend/'
        - 'frontend/'
    - name: 'Create SSL directory'
      become: yes
      file:
        path: /etc/sahabee.ir/ssl-files/
        state: directory
    - name: 'Copy SSL private key'
      become: yes
      copy:
        src: '{{ lookup("env", "SSL_PRIVATE_KEY_FILE") }}'
        dest: /etc/sahabee.ir/ssl-files/privkey.pem
    - name: 'Copy SSL fullchain'
      become: yes
      copy:
        src: '{{ lookup("env", "SSL_FULL_CHAIN_FILE") }}'
        dest: /etc/sahabee.ir/ssl-files/fullchain.pem
    - name: 'Copy nginx config'
      copy:
        src: '{{ nginx_conf_path }}'
        dest: '{{ dest_root_dir }}/'
    - name: 'Login to Docker Hub registry (To extend pull rate limit)'
#      shell: 'echo {{ docker_hub_password | mandatory }} | docker login -u {{ docker_hub_username | mandatory }} --password-stdin'
      community.general.docker_login:
        username: '{{ docker_hub_username | mandatory }}'
        password: '{{ docker_hub_password | mandatory }}'
    - name: 'Pull, Stop, and Start containers'
      docker_compose:
        project_src: '{{ dest_root_dir }}'
        build: no
        pull: '{{ item.pull }}'
        state: '{{ item.state }}'
      environment:
        API_VERSION: '{{ api_version }}'
        FRONTEND_VERSION: '{{ frontend_version }}'
        PRODUCTION_IP: '{{ ansible_host }}'
        SECRET_KEY: '{{ secret_key }}'
        FULLCHAIN_PATH: /etc/sahabee.ir/ssl-files/fullchain.pem
        PRIVKEY_PATH: /etc/sahabee.ir/ssl-files/privkey.pem
        API_URL: '{{ api_url }}'
      loop:
        - { pull: yes, state: present }
        - { pull: no, state: absent }
        - { pull: no, state: present }
