---
- hosts: all
  tasks:
    - name: 'Copy compose file'
      copy:
        src: '{{ src_root_dir }}/docker-compose.yml'
        dest: '/home/{{ ansible_user }}/sahabee/'
    - name: 'Create backend directory as a hack to make docker-compose work!'
      file:
        path: /home/{{ ansible_user }}/sahabee/backend/
        state: directory
    - name: 'Create SSL directory'
      become: yes
      file:
        path: /etc/sahabee.ir/ssl-files/
        state: directory
    - name: 'Copy SSL private key'
      become: yes
      copy:
        src: '{{ lookup("env", "SSL_PRIVATE_KEY_FILE") }}'
        dest: /etc/sahabee.ir/ssl-files/privkey.pem
    - name: 'Copy SSL fullchain'
      become: yes
      copy:
        src: '{{ lookup("env", "SSL_FULL_CHAIN_FILE") }}'
        dest: /etc/sahabee.ir/ssl-files/fullchain.pem
    - name: 'Copy nginx config'
      copy:
        src: '{{ nginx_conf_path }}'
        dest: '{{ dest_root_dir }}/'
    - name: 'Restart Service If needed'
      docker_compose:
        project_src: '{{ dest_root_dir }}'
        build: no
        pull: yes
        state: present
      environment:
        API_VERSION: '{{ api_version }}'
        PRODUCTION_IP: '{{ ansible_host }}'
        SECRET_KEY: '{{ secret_key }}'
        FULLCHAIN_PATH: /etc/sahabee.ir/ssl-files/fullchain.pem
        PRIVKEY_PATH: /etc/sahabee.ir/ssl-files/privkey.pem
#    - name: 'Check logs'
#      shell: 'cd {{ dest_root_dir }} && docker-compose up --no-build'
#      environment:
#        API_VERSION: '{{ api_version }}'
#        PRODUCTION_IP: '{{ ansible_host }}'
#        SECRET_KEY: '{{ secret_key }}'
#        FULLCHAIN_PATH: /etc/sahabee.ir/ssl-files/fullchain.pem
#        PRIVKEY_PATH: /etc/sahabee.ir/ssl-files/privkey.pem
