---
- hosts: all
  tasks:
    - name: 'Copy compose file'
      copy:
        src: '{{ root_dir }}/docker-compose.yml'
        dest: '/home/{{ ansible_user }}/sahabee/'
    - name: 'Copy SSL private key'
      copy:
        src: '{{ lookup("env", "SSL_PRIVATE_KEY_FILE") }}'
        dest: /etc/ssl-files/privkey.pem
    - name: 'Copy SSL fullchain'
      copy:
        src: '{{ lookup("env", "SSL_FULL_CHAIN_FILE") }}'
        dest: /etc/ssl-files/fullchain.pem
    - name: 'Tear down existing service'
      docker_compose:
        project_src: '/home/{{ ansible_user }}/sahabee/'
        state: absent
      environment:
        API_VERSION: '{{ api_version }}'
    - name: 'Start Service'
      docker_compose:
        project_src: '/home/{{ ansible_user }}/sahabee/'
        pull: yes
        state: present
      environment:
        API_VERSION: '{{ api_version }}'
        PRODUCTION_IP: '{{ ansible_host }}'
        SECRET_KEY: '{{ secret_key }}'
