---
name: Pull Request Workflow
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Build
        run: docker-compose build
      - name: Check Migrations
        run: docker-compose run api sh -c "./manage.py makemigrations --dry-run --check"
      - name: Run Tests
        run: docker-compose run api sh -c 'DJANGO_SETTINGS_MODULE=sahabee.settings ./manage.py test'
