---
name: Restore production database backup
on:
  workflow_dispatch:
    input:
      backup_file_url:
        description: URL to the encrypted backup file
        required: true
jobs:
  restore-production-backup:
    runs-on: ubuntu-20.04
    container:
      image: spy86/ansible:latest
    steps:
      - uses: actions/checkout@v2
      - name: Download backup
        run: wget -O backup.zip ${{ github.event.inputs.backup_file_url }}
      - name: Extract backup
        run: unzip backup.zip # Extracts backup.json.enc
      - name: Decrypt backup
        run: echo "${{ secrets.PRODUCTION_BACKUP_FILE_PASS }}"
          | openssl enc -in backup.json.enc -d -aes-256-cbc -pass stdin
          > deployment/ansible/backup.json
      - name: Restore backup
        working-directory: deployment/ansible/
        run: ansible-playbook restore.yml -i inventory.yml --limit production
          --extra-vars "
          ansible_host=${{ secrets.SAHABEE_SERVER_IP }}
          ansible_user=${{ secrets.SAHABEE_SERVER_USER }}
          sudo_pass=${{ secrets.SAHABEE_SERVER_PASS }}
          proxy_server_host=${{ secrets.PROXY_SERVER_HOST }}
          proxy_server_user=${{ secrets.PROXY_SERVER_USER }}
          proxy_server_pass=${{ secrets.PROXY_SERVER_PASS }}
          "
